# Generated by Django 6.0.5 on 2026-06-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
