# Generated by Django 6.0.5 on 2026-06-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_chunk_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='s3_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
